version: '3.7'
services:
  web:
    build: .
    # image: dilverpro/lessa-frontend:v2
    command: npm run start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"

# docker-compose up